import { User } from './auth.type';

export const sampleUserWithUserType: User[] = [
  {
    firstname: 'John',
    lastname: 'Doe',
    phoneNumber: '09011111111',
    address: '123 Elm Street',
    username: 'johndoe',
    password: 'password123',
    id: 'a1',
    type: 'USER',
  },
  {
    firstname: 'Jane',
    lastname: 'Smith',
    phoneNumber: '09022222222',
    address: '456 Oak Avenue',
    username: 'janesmith',
    password: 'securepass',
    id: 'a2',
    type: 'USER',
  },
  {
    firstname: 'Mike',
    lastname: 'Johnson',
    phoneNumber: '09033333333',
    address: '789 Pine Road',
    username: 'mikej',
    password: 'pass321',
    id: 'a3',
    type: 'USER',
  },
  {
    firstname: 'Emily',
    lastname: 'Davis',
    phoneNumber: '09044444444',
    address: '10 Maple Street',
    username: 'emilyd',
    password: 'mypassword',
    id: 'a4',
    type: 'USER',
  },
  {
    firstname: 'Robert',
    lastname: 'Brown',
    phoneNumber: '09055555555',
    address: '22 Willow Way',
    username: 'robbie',
    password: 'hello123',
    id: 'a5',
    type: 'USER',
  },
  {
    firstname: 'Laura',
    lastname: 'Wilson',
    phoneNumber: '09066666666',
    address: '35 Birch Blvd',
    username: 'lauraw',
    password: 'pass456',
    id: 'a6',
    type: 'USER',
  },
  {
    firstname: 'Chris',
    lastname: 'Martinez',
    phoneNumber: '09077777777',
    address: '48 Cedar Court',
    username: 'chrism',
    password: 'letmein',
    id: 'a7',
    type: 'USER',
  },
  {
    firstname: 'Angela',
    lastname: 'Taylor',
    phoneNumber: '09088888888',
    address: '64 Spruce Lane',
    username: 'angiet',
    password: 'mypw123',
    id: 'a8',
    type: 'USER',
  },
  {
    firstname: 'Daniel',
    lastname: 'Anderson',
    phoneNumber: '09099999999',
    address: '82 Redwood St',
    username: 'danieland',
    password: '123secure',
    id: 'a9',
    type: 'USER',
  },
  {
    firstname: 'Olivia',
    lastname: 'Thomas',
    phoneNumber: '09100000000',
    address: '15 Walnut Drive',
    username: 'oliviat',
    password: 'passpass',
    id: 'a10',
    type: 'USER',
  },
  {
    firstname: 'James',
    lastname: 'Jackson',
    phoneNumber: '09111111111',
    address: '27 Chestnut Road',
    username: 'jamesj',
    password: 'jack123',
    id: 'a11',
    type: 'USER',
  },
  {
    firstname: 'Sophia',
    lastname: 'White',
    phoneNumber: '09122222222',
    address: '90 Hemlock Circle',
    username: 'sophiew',
    password: 'sophiapw',
    id: 'a12',
    type: 'USER',
  },
  {
    firstname: 'William',
    lastname: 'Harris',
    phoneNumber: '09133333333',
    address: '13 Dogwood Way',
    username: 'willh',
    password: 'wildcard',
    id: 'a13',
    type: 'USER',
  },
  {
    firstname: 'Ava',
    lastname: 'Clark',
    phoneNumber: '09144444444',
    address: '8 Magnolia Ave',
    username: 'avac',
    password: 'avapass',
    id: 'a14',
    type: 'USER',
  },
];
